"""Augment the router training set with curated prompts.

Targets the failure modes surfaced by router_benchmark.py on the current
MiniLM-trained head:
  - 'calcul-normatif' label is MISSING (regulatory / IEC / EN / CE prompts
    fall back to chat-fr or shell).
  - 'docker' confused with 'shell' on infra prompts.
  - 'spice' confused with 'chat-fr' on prompts phrased in French.
  - Bilingual FR/EN prompts under-represented across all code domains, so
    the encoder over-fits language as a feature.

Run from the ailiance repo root with the Mac venv (Python 3.12+):
  ~/KIKI-Mac_tunner/.venv/bin/python scripts/augment_router_data.py

Effect: appends ~600 new lines to ~/KIKI-Mac_tunner/data/micro-kiki/classified/
(creating calcul-normatif.jsonl). Then re-run scripts/build_router_data.py
followed by scripts/train_router.py to retrain the head.
"""
from __future__ import annotations

import json
import random
from pathlib import Path

CLASSIFIED_DIR = Path.home() / "KIKI-Mac_tunner/data/micro-kiki/classified"
SEED = 1337

# ---------------------------------------------------------------------------
# Prompt banks — short, varied, in the natural mix of FR + EN the platform
# actually receives. Avoid LLM-style boilerplate ("could you please..."), keep
# them as terse as the real prompts in the existing files.
# ---------------------------------------------------------------------------

CALCUL_NORMATIF = [
    # IEC / EN families
    "Quelles sont les exigences de la norme IEC 61010 pour la sécurité électrique ?",
    "Comment vérifier la conformité CE d'un produit électronique selon EN 55032 ?",
    "Différence entre EN 60950 et EN 62368 pour les équipements IT ?",
    "Distance d'isolement requise par EN 61010-1 pour un produit classe II",
    "Calculer les courants de fuite selon IEC 60601-1 pour un dispositif médical",
    "Comment respecter EN 55011 pour un convertisseur DC-DC industriel ?",
    "Test de surtension selon IEC 61000-4-5 sur une alimentation 24V",
    "Quelle CEM appliquer à un produit IoT vendu en UE — EN 301 489 ?",
    "Tolérance dimensionnelle ISO 2768 pour pièces mécaniques",
    "Marquage CE — différence entre auto-déclaration et notification",
    "Norme IPC-2221 pour le routage des PCB — quelles distances ?",
    "Combien de mm minimum entre piste et bord PCB selon IPC-A-600 classe 2 ?",
    "Calcul de l'épaisseur de cuivre requis pour 5A continu selon IPC-2152",
    "Conformité RoHS — substances interdites et seuils",
    "REACH — dois-je déclarer du plomb dans mes soudures ?",
    "DEEE / WEEE — comment marquer un produit pour le recyclage ?",
    "Norme NF C 15-100 pour installation électrique domestique",
    "Calcul du chemin de propagation thermique selon JEDEC JESD51",
    "Quelle norme pour résistance aux chocs IK10 — IEC 62262 ?",
    "Indice de protection IP67 — quels essais ?",
    "Test d'endurance vibratoire selon IEC 60068-2-6",
    "Conformité ATEX zone 2 — quelles exigences pour un capteur ?",
    "Norme EN ISO 13849 pour la sécurité des machines — niveau PL",
    "Évaluation SIL selon IEC 61508 sur un système de sécurité",
    "Norme ISO 26262 pour automobile — quel ASIL pour un airbag ?",
    "MISRA-C 2012 — règle 8.13 sur les pointeurs const",
    "AUTOSAR vs OSEK pour un ECU automobile",
    "Calcul du derating thermique d'un MOSFET selon JEDEC",
    "Norme EN 50121-3-2 pour CEM ferroviaire embarquée",
    "Conformité ETSI EN 300 328 pour module Bluetooth",
    "FCC Part 15 Subpart B vs EN 55032 — équivalence ?",
    "RED 2014/53/EU — quelles évaluations pour un module radio ?",
    "Calcul de SAR pour un dispositif radio porté près du corps",
    "Quels essais de pré-conformité CEM faire avant le labo ?",
    "Comment monter un capot blindé pour passer EN 55022 classe B ?",
    "Décalage de fréquence d'une horloge — limite EN 55032 quasi-peak",
    "Plan de qualification d'un produit selon IEC 60068 (vibrations, chocs, climat)",
    "Norme UL 94 pour l'inflammabilité d'un boîtier plastique",
    "Calcul HALT/HASS — protocole d'essai accéléré",
    "Quel circuit de protection ESD selon IEC 61000-4-2 niveau 4 ?",
    "Différence Cat I, II, III, IV selon EN 61010 pour multimètres",
    "Norme IEC 60664-1 pour coordination d'isolement basse tension",
    "Comment dimensionner un fusible selon IEC 60127 ?",
    "Calcul du facteur de sécurité d'un transformateur isolant médical",
    "Norme NF C 18-510 — habilitation électrique BR",
    "Évaluation des risques selon EN 12100 pour une machine",
    "Norme ISO 9001 vs ISO 13485 pour dispositifs médicaux",
    "Plan de validation d'un produit selon IEC 62304 logiciel médical",
    "Comment obtenir le marquage CE médical classe IIa ?",
    "Norme EN 60204-1 pour équipement électrique des machines",
    "Distance d'air et de fuite — calcul selon IEC 60664-1",
    "Tableau des classes de pollution IEC 60664 pour PCB en milieu humide",
    "Quel test de robustesse mécanique selon EN 60068-2-27 ?",
    "Calcul de durabilité d'une batterie selon IEC 62133-2",
    "Norme UN 38.3 pour le transport de batteries lithium",
    "Conformité MID 2014/32/UE pour compteurs d'énergie",
    "Norme ISO 20022 pour échange de messages financiers",
    "ITU-T G.703 pour interface E1 télécom",
    "DO-160 pour qualification aéronautique d'un calculateur",
    "Calcul de dose de rayonnement selon IEC 62117",
    "Norme IEC 62443 pour cybersécurité industrielle (OT)",
    "Calcul de coordination des protections selon CEI 60909",
    "Quelle harmonisation EN 50549 pour onduleur photovoltaïque raccordé réseau ?",
    "Norme IEEE 1547 vs EN 50549 sur le couplage réseau",
    "Procédure d'essai foudre IEC 61643 pour parafoudre",
    "Calcul de tenue diélectrique selon EN 61010-1 — produit 230V CE",
    "Comment justifier la conformité EMC selon directive 2014/30/UE ?",
    "Norme ISO 7637-2 pour transitoires électriques sur réseau 12V auto",
    "Calcul de température maximale interne selon IEC 60695-2-11",
    "Class 1 vs Class 2 selon UL 1310 pour alimentation",
    "Norme EN 14604 pour détecteur de fumée domestique",
    "Calcul du retard de coupure d'un disjoncteur selon EN 60898",
    "Norme IEC 62752 pour câble de recharge VE mode 2",
    "Conformité IEC 61851 pour borne de recharge mode 3",
    "Calcul du déséquilibre de phases selon EN 50160",
    "Norme EN 50173 pour câblage générique structuré",
    "Test de pénétration d'eau IPX7 — protocole IEC 60529",
    "Différence IPX5 et IPX6 — débit et durée du jet ?",
    "Calcul de la force de retenue d'un connecteur selon IEC 60068-2-21",
    "Norme EN 14476 pour activité virucide d'un désinfectant",
    "Conformité ATEX 2014/34/UE — catégories 1G, 2G, 3G",
    "Norme IECEx vs ATEX — quelle est la portée ?",
    "Calcul de la grade de protection contre l'humidité selon IEC 60068-2-30",
    "Norme EN 50131 pour systèmes d'alarme intrusion",
    "Calcul du facteur de bruit psophométrique selon ITU-T O.41",
    "Norme ITU-T G.984 pour réseau GPON fibre",
    "Conformité RGPD pour traitement de données IoT",
    "Article 25 RGPD — privacy by design pour produit connecté",
    "Norme ISO/IEC 27001 — quels contrôles pour SMSI ?",
    "Calcul de MTBF selon MIL-HDBK-217 pour électronique embarquée",
    "Norme IEC 60749-23 pour vieillissement accéléré JEDEC",
    "Comment justifier la conformité électrique selon CEI 60364 ?",
    "Norme AFNOR NF S 61-961 pour DAS détecteur autonome",
    "Calcul du niveau de bruit acoustique selon ISO 3744",
    "Norme EN 1149 pour vêtements antistatiques ESD",
    "Conformité RED — module radio < 25 mW vs > 25 mW",
    "Calcul de sensibilité du récepteur selon ETSI EN 300 220",
    "Norme IEC 61784 pour bus de terrain industriel",
    "ProfiNet vs EtherCAT vs Modbus TCP — quelle norme dominante ?",
    "Calcul de latence déterministe selon IEEE 802.1 TSN",
    "Norme IEC 61131-3 langages automate (LD, FBD, ST, IL, SFC)",
    "Procédure de qualification matériaux selon IPC-4101 pour PCB FR4",
    "Calcul de Tg requis selon classe de produit selon IPC-6012",
    "Norme IPC-A-610 — critères d'acceptation soudure classe 2",
    "Différence Class 2 et Class 3 selon IPC-6012 sur plaquages",
    "Calcul de dilatation thermique CTE selon IPC-TM-650",
    "Norme NEMA 4X pour boîtier industriel — équivalent IP66",
    "Norme UL 50E vs NEMA 4X — différence ?",
    "Calcul de l'effort axial sur une vis selon ISO 898-1",
    "Tolérance ISO 2768 fine vs moyenne pour usinage",
    "Norme NF EN 1090 pour éxécution d'ouvrages métalliques",
    "Calcul de fatigue selon Eurocode 3 pour structure soudée",
    "Norme EN ISO 9606 qualification de soudeur",
    "Calcul du diamètre minimal de cintrage de tôle selon EN 14220",
    "Norme EN ISO 14644-1 — classes de salles blanches",
    "Calcul du nombre de particules autorisé en ISO 7 vs ISO 8",
    "Procédure de qualification IQ/OQ/PQ pharmaceutique selon GMP Annexe 15",
    "Norme USP <1058> sur la qualification d'instrument analytique",
    "Calcul de l'incertitude de mesure selon GUM (JCGM 100)",
    "Norme ISO 17025 pour laboratoires d'étalonnage",
    "Procédure d'audit selon ISO 19011 — types I, II, III",
    "Norme EN 13485 — étalonnage des thermomètres pour denrées périssables",
    "Calcul de la classe d'erreur selon IEC 60751 pour Pt100",
    "Norme IEC 62359 pour exposition aux ultrasons médicaux",
    "Calcul de l'impédance acoustique selon ISO 7196",
    "Norme EN 12101 pour désenfumage de bâtiments",
    "Calcul du débit d'extraction selon NF EN 12101-3",
    "Norme NF EN 50272 pour batteries de traction et stationnaires",
    "Calcul de l'autonomie d'un onduleur selon EN 50171",
    "Conformité directive ErP 2009/125/CE — eco-design alimentations",
    "Calcul de l'efficacité Niveau VI selon DOE / EU CoC v5",
    "Norme EN 50436 pour éthylotest anti-démarrage",
    "Calcul de précision selon OIML R51 pour pèse-personne",
    "Norme NF EN 13757 pour télérelève M-Bus / Wireless M-Bus",
    "Quelle norme pour intégration BACnet ASHRAE 135 dans un BMS ?",
    "Calcul de pertes thermiques selon NF EN ISO 6946 pour mur composite",
    "Norme RT 2012 vs RE 2020 — coefficient Bbio",
    "Calcul du Cep maximal selon RE 2020 logement neuf",
    "Norme NF DTU 24.1 pour conduits de fumée",
    "Procédure de validation selon IEC 60601-2-2 — bistouri électrique",
    "Calcul du fuite tolérée selon EN 60601-1 cl. 8.7",
    "Norme EN 13287 pour résistance au glissement des chaussures EPI",
    "Marquage Notified Body 4 chiffres — quelles obligations ?",
    "Norme EN 71-3 sur la migration des éléments dans jouets",
    "Conformité directive jouets 2009/48/CE — quels essais ?",
    "Calcul de la dose d'irradiation selon ISO 11137 pour stérilisation",
    "Norme ISO 11607 pour emballage de dispositifs médicaux stérilisés",
    "Procédure de validation logiciel selon IEC 62304 — classe B",
    "Calcul du SOUP selon IEC 62304 — software of unknown provenance",
    "Norme ISO 14971 pour gestion des risques médicaux",
    "Calcul du score RPN selon AMDEC processus",
    "Norme EN 13501 pour réaction au feu — classes A1 à F",
    "Calcul de la résistance au feu REI 60 selon EN 13501-2",
    "Procédure de qualification selon EN 1990 — Eurocode 0",
    "Norme NF P 01-012 pour garde-corps de bâtiments",
    "Calcul de la charge d'exploitation selon NF EN 1991",
    "Norme NF EN 12150 pour verre trempé thermiquement",
    "Calcul de la flexion selon NF EN 12603 pour vitrage",
    "Norme EN 60529 sur les degrés de protection IK et IP",
    "Différence IK06 et IK08 — énergie d'impact ?",
    "Norme EN 50525 pour câbles d'énergie BT",
    "Calcul de la chute de tension selon NF C 15-100 §525",
    "Procédure de mise à la terre TN-S vs TT selon NF C 15-100",
    "Norme EN ISO 4628 pour évaluation des défauts de peinture",
    "Calcul du coefficient d'absorption acoustique selon ISO 354",
    "Norme NF S 31-080 pour acoustique de bureau",
    "Calcul du temps de réverbération selon Sabine",
    "Procédure d'essai de pull-out selon IEC 60068-2-21",
    "Norme IEC 61300 pour composants optiques fibrés",
    "Calcul du retour de perte selon ITU-T G.652",
    "Norme IEEE 802.3bt pour PoE++ classe 8 (90W)",
    "Calcul du dérating PoE selon IEEE 802.3bt — Type 4",
    "Norme EN 50173-1 — câblage classe E vs classe F",
    "Calcul de l'atténuation Cat6A selon TIA-568",
    "Procédure de certification ANSI/TIA-568.0-D — niveau IV",
    "Norme EN 50174 pour installation de câblage métallique",
    "Calcul du rayon de courbure mini d'une fibre OM4",
    "Norme TIA-942 pour data center — Tier I à Tier IV",
    "Calcul du PUE — Power Usage Effectiveness",
    "Norme EN 50600 pour facilités de data center",
    "Procédure de validation thermique selon ASHRAE TC 9.9",
    "Calcul de la classe Allowable Environment selon ASHRAE",
    "Norme NEBS Level 3 pour équipement télécom",
    "Procédure de qualification sismique selon GR-63-CORE",
    "Norme EN 50121 pour CEM ferroviaire — partie 4 systèmes signalisation",
    "Calcul de la distance d'arc électrique selon NFPA 70E",
    "Norme NF C 17-200 pour installations d'éclairage extérieur",
    "Calcul du gradient de potentiel selon CEI 60099",
    "Norme IEC 62305 pour protection foudre — niveaux LPL I à IV",
    "Calcul de la zone protégée selon IEC 62305-3",
    "Procédure d'essai impulsion 1.2/50 µs selon IEC 60060-1",
    "Norme IEC 60076 pour transformateurs de puissance",
    "Calcul du Vk court-circuit selon IEC 60076-5",
    "Norme IEC 60947 pour appareillage industriel BT",
    "Calcul du pouvoir de coupure Icu vs Ics selon IEC 60947-2",
    "Norme NF EN 60439 — ensembles d'appareillage TGBT",
    "Calcul des courants Icc selon CEI 60909 méthode des composantes symétriques",
    "Procédure de tropicalisation selon IEC 60068-2-30",
    "Norme MIL-STD-810 — méthode 506 pluie",
    "Calcul du coefficient de durabilité salin selon MIL-STD-810 méthode 509",
    "Norme MIL-STD-461 RE102 pour émissions rayonnées",
    "Calcul de la marge de bruit selon MIL-STD-461 CE102",
    "Norme DO-178C pour logiciel aéronautique — DAL A à E",
    "Calcul de couverture MC/DC selon DO-178C niveau A",
    "Norme DO-254 pour matériel programmable aéronautique",
    "Procédure de qualification selon RTCA DO-160G — section 22 induced signal",
    "Norme IEC 61326 pour CEM des équipements de mesure",
    "Calcul de l'immunité conduite selon IEC 61000-4-6",
    "Procédure d'essai selon IEC 61000-4-3 — champ rayonné 80 MHz à 1 GHz",
    "Norme IEC 61000-4-4 pour transitoires rapides en salves",
    "Calcul du niveau de signal selon CISPR 22 / EN 55022",
    "Comment respecter UNE 211002 pour câbles BT en Espagne ?",
    "Norme DIN VDE 0100 pour installations BT — Allemagne",
    "Calcul du courant de court-circuit selon BS 7671 — UK",
    "Norme NEMA TS-2 pour contrôleurs de signalisation routière",
    "Calcul de la robustesse selon SAE J1455 environnement camion",
    "Procédure ISO 16750 pour CEM auto 12V/24V",
    "Norme ISO 11898 pour bus CAN — couches PHY",
    "Calcul de la longueur max d'un bus CAN à 500 kb/s",
    "Norme SAE J2602 pour LIN bus auto",
    "Procédure de qualification selon AEC-Q100 grade 1 pour IC auto",
    "Norme AEC-Q200 stress test passive components",
    "Calcul de la durée de vie selon AEC-Q104 multi-die module",
]

DOCKER_AUG = [
    "Comment écrire un Dockerfile multi-stage pour réduire la taille d'une image Python ?",
    "Différence entre COPY et ADD dans un Dockerfile ?",
    "Best practices pour gérer les secrets dans Docker Compose",
    "How do I dockerize a FastAPI application with SQLAlchemy?",
    "Pourquoi mon container Docker ne peut pas accéder au réseau ?",
    "Optimize a Dockerfile to use BuildKit cache mounts",
    "Comment faire fonctionner Docker Compose avec un .env partagé ?",
    "Set up healthcheck on a Postgres container in compose",
    "Différence entre Docker volume et bind mount",
    "Comment limiter la RAM d'un container Docker ?",
    "Docker on Mac M1 — pull amd64 image how?",
    "How to mount /var/run/docker.sock safely in a container?",
    "Set up rootless Docker on Ubuntu 24.04",
    "Quelle différence entre ENTRYPOINT et CMD ?",
    "Pourquoi Docker COPY échoue avec context relatif ?",
    "Configure Docker logging driver to send to Loki",
    "How do I tag and push an image to GHCR?",
    "Use docker buildx to cross-build arm64 from amd64",
    "Compose v2 vs Compose v1 — migration steps",
    "Set up HEALTHCHECK CMD in alpine slim image",
    "Pourquoi mon Dockerfile prend 30 minutes à build ?",
    "Reduce final image size — distroless or alpine?",
    "Multi-arch image build with docker manifest",
    "Comment faire pour qu'un user non-root puisse écrire dans /app ?",
    "Docker Swarm vs Kubernetes — when to choose what?",
    "Run a one-off command in a running container",
    "Docker exec into a stopped container — possible?",
    "Pourquoi docker compose down delete mes volumes ?",
    "Container not pickup new env var — how to refresh?",
    "Restart policy: always vs unless-stopped vs on-failure",
    "Compose depends_on vs healthcheck condition",
    "How do I use a private registry with docker login?",
    "Set up Watchtower to auto-update containers",
    "Comment debugger un container qui crash au démarrage ?",
    "View Docker daemon logs on Linux systemd",
    "Reduce log volume — set max-size and max-file in daemon.json",
    "Pourquoi docker pull est lent ? configurer un mirror",
    "Use Docker Compose profiles for dev vs prod",
    "Network mode host vs bridge vs none — quel choisir ?",
    "Docker 4-stage build for a Go binary < 10 MB",
    "How to run X11 GUI app in Docker with display forwarding?",
    "Run docker compose with override file for dev",
    "Container DNS resolution failing — investigate",
    "Pourquoi mon volume Docker est en read-only ?",
    "How to use bind-mount with SELinux enabled (z option)?",
    "Pin base image by digest for reproducibility",
    "Multi-tenant Docker setup — userns-remap configuration",
    "Comment monter un secret Docker au runtime ?",
    "Resource limits — cpus, mem_limit, pids_limit in compose",
    "Set up a private Docker registry with HTTPS",
    "Use docker scout to scan an image for CVEs",
    "Comment faire un pre-pull d'image au boot via systemd ?",
    "Docker logs growing fast — rotate via daemon.json",
    "Pourquoi BuildKit cache miss à chaque build ?",
    "Use --cache-from with GitHub Actions cache",
    "How to bind to specific GPU with docker run --gpus?",
    "Comment passer une variable d'env au build (ARG vs ENV)",
    "Pourquoi mon container redémarre en boucle ?",
    "Set up nginx reverse proxy in front of FastAPI containers",
    "Compose extends — réutiliser la même config",
    "How to handle multiple compose files (-f flag chaining)?",
    "Networks in compose — internal vs external mode",
    "Comment scaler un service compose à 5 réplicas locaux ?",
    "Docker context — switching between local and remote daemon",
    "Use SSH agent forwarding inside docker run for git clone",
    "Comment reset Docker complètement sur Mac (system prune all)",
    "Container time differs from host — fix timezone",
    "Set tmpfs mount for /tmp speedup",
    "Why does docker stats show 0 memory usage?",
    "Pourquoi docker compose up monte mais Service refuse les connexions ?",
    "Use init: true to handle SIGTERM properly",
    "Compose run vs up — quand utiliser lequel ?",
    "How to inspect layers of a Docker image (dive tool)",
    "Build cache busting via ARG VERSION",
    "Docker Compose health check timeout / interval / retries — values",
    "Pourquoi Docker met si longtemps à pull une layer ?",
    "Comment override entrypoint au runtime ?",
    "Running cron jobs inside Docker — best approach",
    "Use ofelia for cron in Docker Compose",
    "Comment gérer logging multiline en Docker (Java stack traces) ?",
    "Set up Loki + Promtail + Grafana for Docker logs",
    "Why does my container have no /tmp space (overlay full)?",
    "How to add a CA cert to a Debian-based image",
    "Compose extra_hosts — quand utiliser ?",
    "Pourquoi mon network compose ne résout pas les noms de service ?",
    "Use docker network connect to attach a running container",
    "Comment faire un Dockerfile basé sur scratch pour Go ?",
    "Use STOPSIGNAL to override default SIGTERM",
    "Compose secrets vs env_file — différence sécurité",
    "How to inspect environment variables of a running container",
    "Pourquoi mon image fait 2 GB pour une app Python 50 MB ?",
    "Use docker history to find big layers",
    "ARG vs ENV — quelles différences au runtime",
    "Comment mounter un read-only filesystem dans le container ?",
    "Use CAP_DROP=ALL pour container hardening",
    "AppArmor profile pour Docker — comment configurer ?",
    "Comment passer la timezone Europe/Paris à un container ?",
    "How to connect docker compose to existing external network",
    "BuildKit secret mount — pour npm/pip auth tokens",
    "Comment mesurer le démarrage d'un container (entrypoint timing) ?",
    "Use docker compose convert to inspect resolved config",
    "How to use docker compose on a remote machine via SSH context",
    "Docker daemon won't start after upgrade — debug socket file",
]

SPICE_AUG = [
    "Simule un filtre RC dans NGSPICE",
    "Comment modéliser un transistor BJT en SPICE ?",
    "Run a transient analysis on this op-amp circuit in SPICE",
    "Code SPICE pour analyser un convertisseur Buck",
    "Compare LTspice vs NGSpice pour la simulation analogique",
    "Comment écrire un .subckt pour un AOP TL081 en NGSPICE ?",
    "Analyse AC d'un filtre passe-bande LC en SPICE",
    "How to perform Monte Carlo analysis in SPICE for tolerance?",
    "Simulation paramétrée d'un diviseur de tension SPICE",
    "Pourquoi ma simulation NGSPICE ne converge pas ?",
    "Adjust .options reltol abstol vntol pour convergence",
    "How to plot transient FFT in NGSpice",
    "SPICE model pour MOSFET IRF540 — où trouver ?",
    "Simulation d'un oscillateur Wien en SPICE",
    "Comment faire un .step param en LTspice pour balayer une résistance ?",
    "Run a noise analysis on a low-noise amplifier in SPICE",
    ".tran 0 1ms 0 10us — paramètres d'analyse transient",
    "How to set initial conditions on a capacitor in SPICE",
    "Comment importer un modèle SPICE de Texas Instruments dans LTspice ?",
    "Simulation thermique SPICE — équivalent thermique-électrique",
    "Sweep DC d'une diode pour tracer sa caractéristique I-V",
    "Comment simuler un buck converter avec contrôle PWM en LTspice ?",
    "Modélisation small-signal vs large-signal en SPICE",
    "Run a pole-zero analysis to check stability in SPICE",
    "Pourquoi LTspice donne un résultat différent de NGSPICE ?",
    "Modèle SPICE Berkeley BSIM4 pour MOSFET 65nm",
    "Comment faire une analyse paramétrique sur la fréquence en SPICE ?",
    "Simulation harmonic balance en SPICE RF",
    "How to model a switching transformer in SPICE",
    "Comment modéliser le bruit 1/f d'un AOP en SPICE ?",
    "Use a behavioral source (B element) in NGSPICE for non-linear function",
    "Convergence helper — adding small G_min between nodes",
    "Comment simuler le phase-noise d'un VCO en SPICE ?",
    "Mesure de THD avec .four 1k 9 — interpréter résultats",
    "Simulation transitoire d'un démarrage soft-start convertisseur",
    "How to apply step input in SPICE — PULSE source syntax",
    "Comment placer une condition initiale sur un nœud en SPICE ?",
    "Quel solveur GMIN-stepping vs source stepping en convergence ?",
    "Simulation EMI d'un buck — bridging avec NGSPICE-FFT",
    "Comment générer un fichier de stimulus PWL en SPICE ?",
    "Macro model AOP TL082 — bandwidth + slew rate",
    "Simulation d'un PLL boucle à verrouillage de phase en SPICE",
    "How to plot the locus of poles vs a swept parameter?",
    "Comment ajouter un coupling capacitif parasite entre traces en SPICE ?",
    "Modélisation d'une inductance avec ESR et auto-résonance",
    "Comment calculer le rendement d'un push-pull en SPICE ?",
    "Use .ic vs .nodeset pour fixer un point de fonctionnement",
    "Run a worst-case analysis with min/max parameters",
    "Comment exporter les résultats SPICE en CSV pour Python ?",
    "Simulation d'un amplificateur classe AB en SPICE",
    "Modélisation d'une LED avec sa courbe V-I en SPICE",
    "How to simulate a relaxation oscillator in SPICE",
    "Comment modéliser un transformateur idéal vs réel en SPICE ?",
    "Simulation d'un rectifier full-bridge avec ripple",
    "Analyse de Bode automatique en LTspice — .ac dec puis plot",
    "Comment vérifier la stabilité d'un AOP en boucle fermée (Tian probe) ?",
    "SPICE simulation of a Class-D audio amp",
    "Comment écrire un modèle Spice pour un cristal quartz ?",
    "Simulation transitoire d'un flyback avec snubber RCD",
    "Mesure du gain en boucle ouverte d'un AOP via injection",
    "How to model temperature dependence of resistor in SPICE",
    "Tempco TC1 TC2 sur résistance — syntaxe SPICE",
    "Comment paramétrer une simulation de durée variable en SPICE ?",
    "Use .save expression to save only one node",
    "SPICE batch run — multiple .cir files via Python wrapper",
    "Comment faire un sweep température -40°C à +85°C en LTspice ?",
    "Simulation de cross-talk PCB capacitif/inductif en SPICE",
    "Modèle SPICE d'un connecteur RJ45 avec parasites",
    "How to simulate ESD discharge on input pin in SPICE",
    "Modélisation IBIS-SPICE d'un buffer DDR",
    "Comment importer un modèle IBIS dans LTspice ?",
    "Tracer le rendement d'un buck en fonction du courant de sortie",
    "Comment simuler le bruit de quantification d'un ADC SAR en SPICE ?",
    "Modélisation comportementale d'un ADC en SPICE — équations",
    "Simulation Mixed-mode digital + analog en NGSPICE",
    "Use XSPICE code models pour signal mixé",
    "Comment modéliser un opto-coupleur 4N35 en SPICE ?",
    "Simulation EMC pré-conformité — mesure du bruit conduit en SPICE ?",
    "How to simulate ground bounce on a multi-layer PCB in SPICE",
    "Modèle SPICE pour câble coaxial 50 Ω — transmission line",
    "Tlines vs lossy LTRA — quel choisir en simulation high-speed ?",
    "Comment ajuster le step pour réduire le temps de simulation transitoire ?",
    "Simulation impulse response et group delay en SPICE",
    "Modélisation d'un BAW filter en SPICE 5G",
    "How to embed a Python script for post-processing SPICE results",
    "Comment lancer NGSPICE en batch via la ligne de commande ?",
    "Génération de Smith chart à partir de simulation S-param SPICE",
    "Use mc1.subckt pour Monte Carlo Mismatch en LTspice",
    "Comment simuler un filtre Butterworth ordre 4 actif en SPICE ?",
    "Tools to convert KiCad schematic to SPICE netlist",
    "Comment faire un design corner Slow-Fast/Fast-Slow MOSFET ?",
    "Sensibilité paramétrique en SPICE — .sens analysis",
    "Comment modéliser un PFC boost avec contrôle CCM en SPICE ?",
    "Simulation harmonic distortion d'un amplificateur audio en SPICE",
    "Modèle SPICE TVS diode pour suppression d'ESD",
    "How to simulate an EMI common-mode choke effect in SPICE",
    "Comment ajouter un bruit blanc gaussien en source SPICE ?",
    "Simulation switching MOSFET avec parasitic Lpkg, Cgs, Cgd",
    "Time-domain reflectometry simulation in SPICE for PCB trace",
]

# Mixed FR/EN prompts — test the encoder's ability to handle code-switching
# common in real engineering teams. Each entry is (prompt, target_domain).
MIXED_FR_EN: list[tuple[str, str]] = [
    ("Comment utiliser asyncio en Python pour async functions ?", "python"),
    ("Best practice pour handling exceptions dans une application Flask", "python"),
    ("Write a Python function pour parser un CSV file", "python"),
    ("Comment gérer le borrow checker en Rust pour async tasks ?", "rust"),
    ("Implement a Rust trait pour serialize JSON data", "rust"),
    ("Hello, peux-tu m'aider à understand mon problème ?", "chat-fr"),
    ("Comment faire un git rebase interactive en SQL migration ?", "sql"),
    ("Optimize this query — il prend 5 seconds en prod", "sql"),
    ("How do I configure nginx pour reverse proxy une FastAPI ?", "devops"),
    ("Comment dockeriser une app TypeScript avec un Dockerfile multi-stage ?", "docker"),
    ("Set up a CI pipeline pour deploy automatic sur prod", "devops"),
    ("Comment debugger un memory leak en Node.js avec heap snapshot ?", "typescript"),
    ("Write a TypeScript type guard pour valider du JSON", "typescript"),
    ("Comment configurer ESLint avec TypeScript strict mode ?", "typescript"),
    ("Aide-moi à porter ce snippet Python en Rust pour la performance", "rust"),
    ("How do I optimize a Rust binary pour réduire la taille ?", "rust"),
    ("Comment passer une env var au build ARG dans un Dockerfile ?", "docker"),
    ("Run a pytest avec verbose et coverage en parallèle", "python"),
    ("Comment faire un mock async en pytest avec pytest-asyncio ?", "python"),
    ("Sample d'utilisation FastAPI avec Pydantic v2 — exemple complet", "python"),
    ("Comment connect un Postgres via SQLAlchemy 2.0 async ?", "python"),
    ("Set up a Vite project avec React 19 et Tailwind 4", "web-frontend"),
    ("Comment intégrer un store Zustand avec React Query ?", "web-frontend"),
    ("Comment implémenter rate limiting en Node.js Express ?", "web-backend"),
    ("Build a GraphQL API avec Apollo Server 4 et TypeScript", "web-backend"),
    ("Comment configurer un buck converter pour 5V→3.3V à 1A en LTspice ?", "spice"),
    ("Simulate a low-pass filter en NGSPICE avec corner frequency 1kHz", "spice"),
    ("Comment dimensionner un MOSFET pour switching à 100kHz ?", "power"),
    ("Calculate inductor saturation current pour un buck à 2A peak", "power"),
    ("Comment design un PCB avec un microcontrôleur ESP32-S3 et BLE ?", "embedded"),
    ("Set up a STM32CubeIDE project avec FreeRTOS et un task de blink LED", "stm32"),
    ("Comment programmer un GPIO en bare-metal STM32F4 sans HAL ?", "stm32"),
    ("Implement an I2C driver en C++ pour ESP-IDF", "embedded"),
    ("Comment configurer NGINX avec un certificat Let's Encrypt auto-renew ?", "devops"),
    ("Set up Prometheus alert rules pour high CPU et low disk", "devops"),
    ("How do I write a Bash script pour parser des logs JSON streamés ?", "shell"),
    ("Comment faire un pipeline awk pour extraire des champs CSV ?", "shell"),
    ("Write a YAML schema pour validation OpenAPI 3.1", "yaml-json"),
    ("Comment merger deux fichiers JSON avec jq ?", "yaml-json"),
    ("Build a CSS grid layout avec responsive breakpoints", "html-css"),
    ("Comment animate un element en CSS sans transition jank ?", "html-css"),
    ("Set up a SQL migration pour add a column NOT NULL avec default", "sql"),
    ("Optimize a SELECT JOIN avec EXPLAIN ANALYZE en PostgreSQL", "sql"),
    ("Comment tuner le BSP d'un STM32 pour low-power deep sleep ?", "embedded"),
    ("Implement a CAN bus message parser en Rust pour STM32 embedded", "embedded"),
    ("Comment debugger un schématique KiCad avec ESP32-S3 et antenna ?", "stm32"),
    ("Calculate the current draw d'un Wi-Fi module en transmit mode", "iot"),
    ("Comment intégrer un module LoRa SX1262 avec Pico W ?", "iot"),
    ("Implement an MQTT publisher en MicroPython pour ESP32", "iot"),
    ("Comment faire un diff git en couleur pour les changes binaires ?", "shell"),
    ("Set up a SystemD service pour auto-restart une Python app", "shell"),
    ("Comment configurer un VLAN sur Ubuntu Server avec netplan ?", "devops"),
    ("Run a Lighthouse audit pour une PWA avec service worker", "web-frontend"),
    ("Comment implémenter SSE en Node.js avec une queue Redis ?", "web-backend"),
    ("Build a Stripe webhook handler avec signature verification", "web-backend"),
    ("Comment générer une migration Prisma à partir d'un schema ?", "sql"),
    ("Optimize an OpenAPI spec avec composants reusable et discriminator", "yaml-json"),
    ("Comment écrire un Dockerfile multi-stage pour Rust binary minimal ?", "docker"),
    ("Comment encoder un audio en MP3 avec ffmpeg via une queue Celery ?", "music-audio"),
    ("Implement a real-time DSP filter en Rust pour audio processing", "dsp"),
    ("Comment design un FIR filter avec scipy et plot frequency response ?", "dsp"),
    ("Calculate the FFT d'un signal échantillonné à 48kHz en NumPy", "dsp"),
    ("Comment quantifier un modèle PyTorch en INT8 pour edge deployment ?", "ml-training"),
    ("Train a small classifier avec Hugging Face Transformers et PEFT", "ml-training"),
    ("Comment fine-tuner Qwen 1.5B avec LoRA sur un dataset 10k examples ?", "ml-training"),
    ("Setup llama.cpp avec CUDA backend pour inference 70B model", "llm-orch"),
    ("Comment écrire un agent LangChain avec un custom tool ?", "llm-orch"),
    ("Build a vector store avec ChromaDB et Sentence Transformers", "llm-orch"),
    ("Comment compute embeddings batch avec Jina v3 sur GPU ?", "llm-orch"),
    ("Set up FreeCAD avec Python scripting pour générer des pièces 3D", "freecad"),
    ("Comment exporter un STEP file depuis un FreeCAD assembly ?", "freecad"),
    ("Comment simuler un circuit RLC série en LTspice avec sweep frequency ?", "spice"),
    ("Run an EM simulation pour antenna patch en HFSS — alternatives open source ?", "electronics"),
    ("Comment dimensionner les pull-up I2C selon datasheet et capacitance ?", "electronics"),
    ("Calculate the RC time constant pour debouncing a switch", "electronics"),
    ("Comment configurer une PMU pour une carte STM32 avec sleep mode et wake-up RTC ?", "power"),
    ("Battery sizing pour un IoT device avec duty cycle 1% et 1mA active", "power"),
    ("Comment auditer la sécurité d'une API REST avec OWASP ZAP ?", "security"),
    ("Set up Vault pour secret management avec Kubernetes auth", "security"),
    ("Comment implementer un JWT validator en Python avec rotation des keys ?", "security"),
    ("Implement OAuth2 PKCE flow en TypeScript pour SPA", "security"),
    ("Comment poser un Lua script dans MicroPython pour un capteur I2C ?", "lua-upy"),
    ("Write a MicroPython driver pour SHT4x sensor", "lua-upy"),
    ("Comment faire un timer software en MicroPython pour ESP32 ?", "lua-upy"),
    ("Comment design un VST audio plugin en C++ avec JUCE ?", "music-audio"),
    ("Implement a synthesizer voice avec wavetable en C++", "music-audio"),
    ("Comment générer un MIDI file programmatiquement en Python ?", "music-audio"),
    ("Comment annoter un schéma KiCad avec un script Python via kicad-python ?", "kicad-dsl"),
    ("Generate a PCB layout avec atopile DSL pour rapid prototyping", "kicad-dsl"),
    ("Comment écrire un footprint custom en KiCad 9 pour un connecteur USB-C ?", "kicad-pcb"),
    ("Calculate impedance d'une trace différentielle 100Ω en KiCad", "kicad-pcb"),
    ("Comment configurer le DRC en KiCad avec custom rules ?", "kicad-pcb"),
    ("Comment créer un projet PlatformIO pour ESP32-S3 avec CMake ?", "platformio"),
    ("Set up multi-environment dans platformio.ini pour dev et release", "platformio"),
    ("Comment programmer un STM32G4 en bare-metal avec GCC arm-none-eabi ?", "embedded"),
    ("Implement DMA transfer pour ADC en STM32 HAL", "stm32"),
    ("Comment configurer un timer en input capture mode en STM32 ?", "stm32"),
    ("Solve a linear system Ax=b avec NumPy SciPy en mode sparse", "math"),
    ("Comment compute eigenvalues d'une matrice 1000x1000 efficiently ?", "math"),
    ("Implement a Newton-Raphson solver en Python pour une équation non-linéaire", "math"),
    ("Comment expliquer step-by-step la dérivation de la loi de Bayes ?", "reasoning"),
    ("Walk me through the logic d'un puzzle d'inférence avec contraintes", "reasoning"),
    ("Comment résoudre un Sudoku avec backtracking algorithm ?", "reasoning"),
]


def main() -> None:
    random.seed(SEED)
    CLASSIFIED_DIR.mkdir(parents=True, exist_ok=True)

    def write_jsonl(path: Path, prompts: list[str], domain: str, mode: str) -> int:
        with path.open(mode) as f:
            for p in prompts:
                f.write(json.dumps({"prompt": p, "domain": domain}, ensure_ascii=False) + "\n")
        return len(prompts)

    # 1) New domain calcul-normatif
    target = CLASSIFIED_DIR / "calcul-normatif.jsonl"
    n = write_jsonl(target, CALCUL_NORMATIF, "calcul-normatif", "w")
    print(f"calcul-normatif.jsonl : {n} new prompts (file created)")

    # 2) Append docker augmentations
    target = CLASSIFIED_DIR / "docker.jsonl"
    n = write_jsonl(target, DOCKER_AUG, "docker", "a")
    print(f"docker.jsonl          : +{n} appended")

    # 3) Append spice augmentations
    target = CLASSIFIED_DIR / "spice.jsonl"
    n = write_jsonl(target, SPICE_AUG, "spice", "a")
    print(f"spice.jsonl           : +{n} appended")

    # 4) Mixed FR/EN — write to a sidecar file then append per domain
    by_domain: dict[str, list[str]] = {}
    for prompt, dom in MIXED_FR_EN:
        by_domain.setdefault(dom, []).append(prompt)
    total_mixed = 0
    for dom, prompts in sorted(by_domain.items()):
        target = CLASSIFIED_DIR / f"{dom}.jsonl"
        if not target.exists():
            print(f"  WARN: {target.name} doesn't exist, creating it")
        mode = "a" if target.exists() else "w"
        n = write_jsonl(target, prompts, dom, mode)
        total_mixed += n
        print(f"  mixed FR/EN → {dom:18s} +{n}")
    print(f"\nTotal mixed FR/EN appended: {total_mixed}")
    print(
        f"\nGrand total: {len(CALCUL_NORMATIF) + len(DOCKER_AUG) + len(SPICE_AUG) + total_mixed} new prompts"
    )


if __name__ == "__main__":
    main()
